### ISSUE TITLE
Display link to funding transaction when opening a channel

### ISSUE THREAD

**Issue by channelninja** [channelninja/channel.ninja#52]
After opening a channel, channel.ninja only says 'Channel opened successfully'. 

It would be nice to display a link to the funding transaction, so the user can directly check when the channel will be opened.

`request('openchannel')` should return `funding_txid_str` according to the docs but doesn't (https://lightning.engineering/api-docs/api/lnd/lightning/open-channel-sync/index.html)

See: https://github.com/lightningnetwork/lnd/issues/7422

**Comment by channelninja** [comment]
From @rolznz 

>@channelninja looks like we need to decode funding_txid_bytes ourselves.
>
>I managed to get the funding tx by:
Decoding base64 to hex. https://base64.guru/converter/decode/hex
Reversing the hex. https://learnmeabitcoin.com/tools/swapendian
https://learnmeabitcoin.com/technical/txid
>
>(I guess in the code it could be better to reverse the bytes then convert to hex)

**Comment by channelninja** [comment]
@rolznz  I couldn't get this to work with Polar. How did you test it?

**Comment by rolznz** [comment]
@channelninja I created a network with two LND nodes, added 1M sats to the first one (Alice), added it to Alby using the LND connector, then using my sandbox I created a channel to Bob.

https://rolznz.github.io/webln-sandbox/

What part are you having trouble with?

**Comment by channelninja** [comment]
@rolznz I created a network in Polar, opened a channel in channel.ninja and decoded the funding_txid_bytes into the funding tx by converting to hex and then reversing the hex. But now I have some hex that I couldn't verify, if it is a valid tx id. I tried hooking a local mempool.space docker up to my local Polar network. But that didn't work somehow. When I tried to query my Polar bitcoin-core for the tx id, it didn't find it.

**Comment by rolznz** [comment]
@channelninja what commands did you use to find the tx ID? I've never done this myself but am happy to have a look.

**Comment by channelninja** [comment]
@rolznz I used the tools you linked to test it

> Decoding base64 to hex. https://base64.guru/converter/decode/hex
Reversing the hex. https://learnmeabitcoin.com/tools/swapendian

**Comment by rolznz** [comment]
@channelninja I managed to find my one using getrawtransaction (https://developer.bitcoin.org/reference/rpc/getrawtransaction.html)

curl --location --request POST 'http://127.0.0.1:18443' \
--header 'content-type: text/plain;' \
--header 'Authorization: Basic cG9sYXJ1c2VyOnBvbGFycGFzcw==' \
--data-raw '{"jsonrpc": "1.0", "id": "curltest", "method": "getrawtransaction", "params": ["967fdc0f8eb8824701066b0d716e31c11a37e6b5e4c8eb529f23d1b98de0c78e"]}'

The hex param I passed is the reversed hex of the funding transaction. Does that work for you?

**Comment by rolznz** [comment]
Note: You can also call webln.request("gettransactions"). The funding TX should be the first entry, and it will already be in the valid hex format (no need to decode from base64/reverse the hex)

**Comment by channelninja** [comment]
@rolznz I figured out how to test it locally! I got mempool.space to run locally with Polar and the tx id shows up correctly! 

Feature coming soon 🤙
